remote_theme: b2a3e8/jekyll-theme-console
title: root@nothing4free:/#
description: hack the planet!
markdown: kramdown

header_pages:
  - index.md
  - about.md
style: dark
listen_for_clients_preferred_style: true
footer: 'hack the planet! | nothing4free'
