remote_theme: nothing4free/n4free-jekyll-theme-console
title: root@nothing4free:/#
description: hack the planet!
markdown: kramdown

header_pages:
  - index.md
  - posts.md
  - project_elliot.md
  - legacy.md
  - about.md

style: dark
listen_for_clients_preferred_style: true
header: 'nothing4free'
footer: 'hack the planet! | <a href="https://github.com/nothing4free">github</a> | <a href="https://twitter.com/n4free_">twitter</a>'

BASE_PATH: /

collections:
  legacy:
    output: true